language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite db_dsn='sqlite:///:memory:'

  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.1
      env: PHPCS=1 DEFAULT=0

    - php: 7.1
      env: STATIC_ANALYSIS=1 DEFAULT=0

    - php: 7.1
      env: PREFER_LOWEST=1

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]]; then phpenv config-rm xdebug.ini; fi

  - if [[ $PREFER_LOWEST != 1 ]]; then composer update --no-interaction; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --no-interaction --prefer-lowest --prefer-stable; fi

  - if [[ $DB = 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB = 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

  - if [[ $PHPCS = 1 ]]; then composer require cakephp/cakephp-codesniffer:dev-next; fi

script:
  - |
      if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.1 ]]; then
        mkdir -p build/logs
        vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
      fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.1 ]]; then vendor/bin/phpunit; fi

  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

  - if [[ $STATIC_ANALYSIS = 1 ]]; then composer require --dev vimeo/psalm:^3.2 && vendor/bin/psalm src; fi

after_success:
  - |
      if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.1 ]]; then
        wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
        chmod +x php-coveralls.phar
        ./php-coveralls.phar
      fi

notifications:
  email: false
