name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  testsuite:
    uses: ADmad/.github/.github/workflows/testsuite-with-db.yml@master
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  cs-stan:
    uses: ADmad/.github/.github/workflows/cs-stan.yml@master
    secrets: inherit
